@section('sitename'){{$meta['sitename']}}@stop
@section('title'){{$meta['title']}}@stop
@section('url'){{$meta['url']}}@stop
@section('description'){{$meta['description']}}@stop
@section('keywords'){{$meta['keywords']}}@stop
@section('pageimage'){{$meta['pageimage']}}@stop
@section('pageurl'){{$meta['pageurl']}}@stop
@section('publishedTime'){{$meta['publishedTime']}}@stop
@section('modifiedTime'){{$meta['modifiedTime']}}@stop
@section('section'){{$meta['section']}}@stop
@section('category'){{$meta['category']}}@stop
@section('tag'){{$meta['tag']}}@stop
@section('article'){{$meta['article']}}@stop
@section('twittersite'){{$meta['twittersite']}}@stop
@section('urlimage'){{$meta['urlimage']}}@stop